version: 0.0
os: linux
files:
- source: /
  destination: /var/app
hooks:
  AfterInstall:
  - location: scripts/install_dependencies.sh
    timeout: 300
  ApplicationStart:
  - location: scripts/start_bot.sh
    timeout: 60
